package com.planes.kyle;

import java.util.HashMap;

public class AirlineIdentify
{
    /*public static String getAirline(String operatorICAO){
        Statement
    }*/
    /*static final HashMap<String, String> AirlineMapping = new HashMap<>()
    {
        {
            put("AAL", "American Airlines");
            put("ASH", "Mesa Airlines");
            put("JIA", "American Airlines");
            put("PDT", "American Airlines");
            put("ENY", "American Airlines");
            put("DAL", "Delta");
            put("EDV", "Delta");
            put("DL", "Delta");
            put("UAL", "United");
            put("ASQ", "United");
            put("UCA", "United");
            put("AWI", "United");
            put("SWA", "SouthWest");
            put("UPS", "UPS");
            put("FDX", "FedEx");
            put("BAW", "British Airways");
            put("AFR", "Air France");
            put("KLM", "KLM");
            put("FFT", "Frontier");
            put("NKS", "Spirit");
            put("AAY", "Allegiant");
            put("ACA", "Air Canada");
            put("ROU", "Air Canada Rouge");
            put("DHK", "DHL");
            put("BCS", "DHL");
            put("PAC", "Polar Air Cargo (DHL)");
            put("UAE", "Emirates");
            put("QFA", "Qantas");
            put("SIA", "Singapore Airlines");
            put("QTR", "Qatar Airways");
            put("ABX", "ABX Air");
            put("GTI", "Atlas Air");
            put("BOX", "AeroLogic");
            put("AMX", "Aeromexico");
            put("ANZ", "Air New Zealand");
            put("KAL", "Korean Air");
            put("SCX", "Sun Country Airlines");
            put("TSC", "Air Transat");
            put("VIR", "Virgin Atlantic");
            put("VRD", "Virgin America");
            put("ASA", "Alaska Airlines");
            put("AAR", "Asiana");
            put("JBU", "JetBlue");
            put("JAL", "Japan Airlines");
            put("AZA", "Alitalia");
            put("ANA", "All Nippon Airways");
            put("AVA", "Avianca");
            put("DLH", "Lufthansa");
            put("CLX", "CargoLux");
            put("CJT", "Cargojet Airways");
            put("HDA", "Cathay Dragon");
            put("CPA", "Cathay Pacific");
            put("CSN", "China Southern");
            put("CIB", "Condor");
            put("CMP", "Copa Airlines");
            put("EZY", "easy Jet");
            put("MSR", "EgyptAir");
            put("ELY", "El Al");
            put("ETD", "Etihad");
            put("SVA", "Saudia");
            put("ETH", "Ethiopian Airlines");
            put("EVA", "Eva Air");
            put("EWG", "Eurowings");
            put("FJI", "Fiji Airways");
            put("MAU", "Air Mauritius");
            put("FIN", "Finnair");
            put("SAS", "SAS(Scandinaian Airlines)");
            put("CHH", "Hainan Airlines");
            put("IBE", "Iberia");
            put("ICE", "Icelandair");
            put("JST", "JetStar");
            put("CKS", "Kalitta Air");
            put("LAN", "LATAM Chile");
            put("LNI", "Lion Air");
            put("MAS", "Malaysia Airlines");
            put("PAL", "Philippine Airlines");
            put("RYR", "Ryanair");
            put("EIN", "Aer Lingus");
            put("SAA", "South African Airways");
            put("ALK", "SriLankan Airlines");
            put("SWR", "Swiss");
            put("KYE", "SkyLease Cargo");
            put("TAP", "TAP Air Portugal");
            put("THY", "Turkish Airlines");
            put("HVN", "Vietnam Airlines");
            put("VOZ", "Virgin Australia");
            put("WJA", "WestJet");
            put("SKW", "SkyWest Airlines");
            put("THT", "Air Tahiti Nui");
            put("HAL", "Hawaiian");
            put("RPA", "Republic Airways");
            put("JZA", "Air Canada Jazz");
            put("LOF", "Tran States Airlines(TSA)");
            put("GJS", "GoJet Airlines");
            put("CPZ", "Compass Airlines");
            put("ATN", "Air Transport International");
            put("JUS", "USA Jet Airlines");
            put("SOO", "Southern Air(DHL)");
            put("SWG", "Sunwing Airlines");
            put("AIJ", "Interjet");
            put("LXJ", "Bombardier Business Jet Solutions");
            put("TWY", "Sunset Aviation");
            put("EJA", "NetJets");
            put("SKV", "Air Canada");
            put("GJE", "Global Air Charters");
            put("WSW", "Swoop(WestJet)");
            put("USC", "AirNet Express");
            put("LCO", "LATAM Cargo Chile");
            put("VIV", "VivaAerobús");
            put("BSK", "Miami Air International");
            put("EJM", "Executive Jet Management");
            put("COL", "SC Aviation");
            put("LL", "Allegro Airlines");
            put("RSP", "JetSuite");
            put("EDG", "JetEdge");
            put("NGF", "Air Charity Network");
            put("PWA", "Priester Aviation");
            put("PAT", "U.S. Army");
            put("CNS", "Cobalt Air");
            put("GAJ", "Wheels Up");
            put("LAK", "Red Wing");
            put("NRS", "Norwegian Air");
            put("AMF", "Ameriflight");
            put("WGN", "Western Global Airlines");
            put("DPJ", "Delta Private Jets");
            put("SAM", "SAM Colombia");
            put("JTL", "Jet Linx Aviation");
            put("XOJ", "XOJet");
            put("DOJ", "Justice Prisoner and Alien Transportation System");
            put("BKA", "Bankair");
            put("CNK", "Sunwest Aviation");
            put("SPA", "Sierra Pacific");
            put("FWK", "FlightWorks");
            put("PLM", "Wamos Air");
            put("RLI", "Reliant Air");
            put("RCH", "Air Mobility Command (U.S. Air Force)");
            put("RAX", "Royal Air Freight");
            put("SKQ", "Labcorp");
            put("SNC", "Air Cargo Carriers");
            put("LBQ", "Quest Diagnostics");
            put("AZG", "Silk Way West Airlines");
            put("SWD", "Southern Winds Airlines");
            put("CAO", "Air China Cargo");
            put("VTM", "Aeronaves TSM");
            put("OAE", "Omni Air International");
            put("GLF", "Gulfstream Aerospace");
            put("TSU", "Gulf and Carribean Cargo");
            put("DKT", "Sioux Falls Aviation");
            put("VDA", "Volga-Dnepr Airlines");
            put("VBA", "V Bird Airlines Netherlands");
            put("BBA", "Bannert Airlines");
            put("CGE", "Nelson Aviation College");
            put("DRL", "Omni Air Transport");
            put("PVO", "Bearing Supplies Limited");
            put("PKW", "Pak West Airlines");
            put("CNV", "U.S. Navy Reserve Logistic Air Forces");
            put("CSB", "21 Air");
            put("SCM", "American Jet International");
            put("ICV","Cargolux Italia");
            put("WIS", "Paccair");
            put("GPD", "Tradewind Aviation");
            put("PEG", "Pegasus Elite Aviation");
            put("MGE", "Asia Pacific Airlines");
            put("CAL", "China Airlines");
            put("SUP", "Aeronautical Charters");
            put("GEC", "Lufthansa Cargo");
            put("JLG", "Jet Logistics");
            put("CSJ", "Castle Aviation");
            put("FDY", "Sun Air International");
            put("JAS", "Jet Aviation Flight Services");
            put("LAC", "Lockheed Aircraft Corporation");
            put("PLM", "Pullmantur Air");
            put("EGC", "First Wing Aircraft Charter And Maintenance");
            put("GLT", "Aero Charter");
            put("XSR", "Airshare");
            put("KFS", "Kalitta Charters");
            put("KII", "Kalitta Charters");
            put("VTE", "Contour Airlines");
            put("PJC", "Pittsburgh Jet Center");
            put("FLE", "Flair Airlines");
            put("LET", "Aerolineas Ejecutivas");
            put("VMP", "Execujet Scandinavia");
            put("RJE", "Reynolds Jet Management");
            put("GDG", "S.P.Aviation");
            put("IFA","FAI Air Service");
            put("AHO", "Air Hamburg");
            put("AJT", "Amerijet International");
            put("FRH", "ACE Belgium Freighters");
            put("CMB", "U.S. Transprotation Command");
            put("EMD", "Eaglemed");
            put("ABW", "AirBridge Cargo");
            put("FRG", "Freight Runners Express");
            put("XLS", "ExcelAire");
            put("JRT", "JetRight");
            put("BTQ", "Boutique Air");
            put("CAP", "USAFX Civil Air Patrol");
            put("CTL", "Central Airlines");
            put("GTH", "General Aviation Flying Services");
            put("CWG", "Clear Wing");
            put("BOE", "Boeing");
            put("ADB", "Antonov Airlines");
            put("SWQ","Swift Air");
            put("FTH", "Mountain Aviation");
            put("VOI", "Volaris");
            put("TNO", "AeroUnion");
            put("ECJ", "East Coast Jets");
            put("NUS", "North Illinois Flight Center");
            put("FSR", "The Flightstar");
            put("KFB", "Superior Transportation Associates");
            put("SLH", "Silverhawk Aviation");
            put("UJC", "Ultimate Air Shuttle");
            put("WAL", "World Atlantic Airlines");
            put("NSH", "Sterling Aviation");
            put("NCR", "National Airlines");
            put("CXB", "Comlux Aruba");
            put("TFF", "Talon Air");
            put("LGT", "Longtail Aviation");
            put("WDW", "Act Two");
            put("FFL", "ForeFlight");
            put("RVJ", "Aircraft Management Group");
            put("YEL", "Summit Aviation");
            put("WDY", "Chicago Jet Group");
            put("MJS", "My Jet Saver");
            put("SIS", "Silver Air");
            put("ERY", "Sky Quest");
            put("MAD", "Malone AirCharter");
            put("XAA", "ARINC");
            put("JCM", "Secure Air Charter");
            put("DCM", "Fltplan");
            put("TMC", "Travel Management Company Ltd.");
            put("CHR", "Chairman Airmotive II, LLC");
            put("SVL", "Alante Air Charter");
            put("WWI", "Worldwide Jet Charter");
            put("CVF", "Dassault Falcon Jet");
            put("BAF", "Belgian Air Force");
            put("FTD", "Ab Jets");
            put("OKC", "Private Jets");
            put("LKF", "Aviation Advisor");
            put("TLK", "Starlink Aviation");
            put("IFL", "IFL Group");
            put("MVJ", "Mira Vista Aviation");
            put("SUB", "Suburban Air Freight");
            put("WML", "Chantilly Air");
            put("TOR", "flyGTA");
            put("SHE", "Shell Aircraft");
            put("FLC", "US Department of Transport, Federal Aviation Administration, Flight Inspection Services");
            put("DOW", "Best Jets International");
            put("SDU", "Dumont Aviation");
            put("PRY", "Priority Air Charter");
            put("HRT", "Chartright Air");
            put("PRD", "Presidential Aviation");
            put("GTW", "American Air Charter");
            put("CTF", "Cutter Aviation");
            put("CVK", "Cavok Air");
            put("CFT", "Jet Freighters");
            put("CRE", "Jet Out");
            put("JNY", "Journey Aviation");
            put("SJA", "Sawyer Aviation");
            put("ABD", "Air Atlanta Icelandic");
            put("WIF", "Wideroe's");
            put("SJJ", "Spirit Jets");
            put("LJY", "L J Aviation");
            put("LTA", "LIFT Academy");
            put("ULA", "Ultraair");
            put("JSP", "Jetstream Aviation");
            put("CYT", "Crystal Air");
            put("RQT", "Airquest Aviation");
            put("ASP", "AirSprint");
            put("SYB", "Skyservice Business Aviation");
            put("BYA", "Berry Aviation");
            put("MDS", "McNeely Charter Services");
        }*/
    };

    public static final String [] emailList = {"BAW", "AFR", "KLM", "UAE", "QFA", "DLH", "SIA", "QTR","KAL"};
    public static final String [] emailTailNumbersList = {"N778AN", "N756US", "N915FJ", "N120EE"};
    public static final String [] emailPlanesList = { "A380", "A350", "A220", "A340", "AN-124", "An-225", "Dreamlifter", "Beluga"};
}
